use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelDefinition {
    pub key: &'static str,
    pub display_name: &'static str,
    pub language_scope: &'static str,
    pub download_url: &'static str,
    pub file_size_bytes: u64,
    pub sha256_checksum: Option<&'static str>,
    pub description: &'static str,
    pub speed: &'static str,
    pub accuracy: &'static str,
    pub category: &'static str,
    pub recommended_for: &'static str,
}

pub static REGISTRY: &[ModelDefinition] = &[
    ModelDefinition {
        key: "ggml-tiny",
        display_name: "Tiny",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin",
        file_size_bytes: 77_704_715,
        sha256_checksum: None,
        description: "Smallest model, runs on any hardware. Limited accuracy but usable for simple dictation.",
        speed: "fastest",
        accuracy: "low",
        category: "standard",
        recommended_for: "Quick tests, very old hardware",
    },
    ModelDefinition {
        key: "ggml-tiny-q8",
        display_name: "Tiny Q8",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny-q8_0.bin",
        file_size_bytes: 43_614_209,
        sha256_checksum: None,
        description: "Tiny quantized to 8-bit. Half the size with nearly identical quality.",
        speed: "fastest",
        accuracy: "low",
        category: "quantized",
        recommended_for: "Minimal RAM, embedded / low-end devices",
    },
    ModelDefinition {
        key: "ggml-tiny-en",
        display_name: "Tiny (EN only)",
        language_scope: "en-only",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin",
        file_size_bytes: 77_704_715,
        sha256_checksum: None,
        description: "English-only Tiny. Slightly better EN accuracy than the multilingual version.",
        speed: "fastest",
        accuracy: "low",
        category: "standard",
        recommended_for: "English-only, minimal resources",
    },
    ModelDefinition {
        key: "ggml-base",
        display_name: "Base",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin",
        file_size_bytes: 147_964_211,
        sha256_checksum: None,
        description: "Good balance of speed and accuracy for everyday dictation. Solid DE/EN support.",
        speed: "fast",
        accuracy: "medium",
        category: "standard",
        recommended_for: "Daily dictation, DE + EN",
    },
    ModelDefinition {
        key: "ggml-base-q8",
        display_name: "Base Q8",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base-q8_0.bin",
        file_size_bytes: 81_773_312,
        sha256_checksum: None,
        description: "Base quantized to 8-bit - 45% smaller, nearly identical accuracy. Great starter model.",
        speed: "fast",
        accuracy: "medium",
        category: "quantized",
        recommended_for: "Best size/quality ratio for Base",
    },
    ModelDefinition {
        key: "ggml-small",
        display_name: "Small",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin",
        file_size_bytes: 487_601_739,
        sha256_checksum: None,
        description: "Noticeably better accuracy than Base, still fast enough for real-time use on modern CPUs.",
        speed: "balanced",
        accuracy: "good",
        category: "standard",
        recommended_for: "Good accuracy without GPU",
    },
    ModelDefinition {
        key: "ggml-small-q8",
        display_name: "Small Q8",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small-q8_0.bin",
        file_size_bytes: 263_819_264,
        sha256_checksum: None,
        description: "Small quantized to 8-bit - 46% smaller with minimal quality loss. Recommended over full Small.",
        speed: "balanced",
        accuracy: "good",
        category: "quantized",
        recommended_for: "Best size/quality ratio for Small",
    },
    ModelDefinition {
        key: "ggml-medium",
        display_name: "Medium",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin",
        file_size_bytes: 1_533_774_855,
        sha256_checksum: None,
        description: "High accuracy for complex vocabulary and accents. Requires ~4 GB RAM. Slower on CPU.",
        speed: "slow",
        accuracy: "great",
        category: "standard",
        recommended_for: "Complex vocabulary, technical terms",
    },
    ModelDefinition {
        key: "ggml-medium-q5",
        display_name: "Medium Q5",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium-q5_0.bin",
        file_size_bytes: 539_212_800,
        sha256_checksum: None,
        description: "Medium at 5-bit quantization - 65% smaller than full Medium, accuracy barely affected.",
        speed: "balanced",
        accuracy: "great",
        category: "quantized",
        recommended_for: "Medium quality at Small size - sweet spot",
    },
    ModelDefinition {
        key: "ggml-large-v3-turbo-q5",
        display_name: "Large v3 Turbo Q5",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q5_0.bin",
        file_size_bytes: 574_000_000,
        sha256_checksum: None,
        description: "Large-v3-Turbo at 5-bit quantization. 8x faster than Large-v3, near-identical accuracy. Best overall pick.",
        speed: "fast",
        accuracy: "best",
        category: "turbo",
        recommended_for: "Best accuracy/speed ratio - recommended",
    },
    ModelDefinition {
        key: "ggml-large-v3-turbo-q8",
        display_name: "Large v3 Turbo Q8",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q8_0.bin",
        file_size_bytes: 874_000_000,
        sha256_checksum: None,
        description: "Large-v3-Turbo at 8-bit quantization. Slightly better than Q5 for noisy audio.",
        speed: "fast",
        accuracy: "best",
        category: "turbo",
        recommended_for: "Noisy environments, high accuracy",
    },
    ModelDefinition {
        key: "ggml-large-v3-turbo",
        display_name: "Large v3 Turbo",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin",
        file_size_bytes: 1_620_000_000,
        sha256_checksum: None,
        description: "Full-precision Large-v3-Turbo (F16). 8x faster than Large-v3, same encoder, only 4 decoder layers.",
        speed: "balanced",
        accuracy: "best",
        category: "turbo",
        recommended_for: "Maximum Turbo accuracy, no quantization",
    },
    ModelDefinition {
        key: "ggml-large-v3-q5",
        display_name: "Large v3 Q5",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-q5_0.bin",
        file_size_bytes: 1_080_000_000,
        sha256_checksum: None,
        description: "OpenAI's best model at 5-bit quantization. State-of-the-art accuracy for all languages.",
        speed: "slow",
        accuracy: "best",
        category: "large",
        recommended_for: "Highest accuracy, powerful hardware",
    },
    ModelDefinition {
        key: "ggml-large-v3",
        display_name: "Large v3",
        language_scope: "multilingual",
        download_url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
        file_size_bytes: 3_100_000_000,
        sha256_checksum: None,
        description: "Full-precision Large-v3 (F16). OpenAI's most accurate Whisper model. Requires ~10 GB RAM.",
        speed: "slowest",
        accuracy: "best",
        category: "large",
        recommended_for: "Maximum accuracy, GPU recommended",
    },
];

pub fn find(key: &str) -> Option<&'static ModelDefinition> {
    REGISTRY.iter().find(|m| m.key == key)
}
