use serde::Serialize;

use crate::transcription::engine::{
    ENGINE_NEMO, ENGINE_PARAKEET_CPP, ENGINE_WHISPER_CPP, FORMAT_GGML_BIN, FORMAT_GGUF,
    FORMAT_NEMO, RUNTIME_BUNDLED_SIDECAR, RUNTIME_OPTIONAL_NEMO,
};

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelDefinition {
    pub key: &'static str,
    pub display_name: &'static str,
    pub language_scope: &'static str,
    pub download_url: &'static str,
    pub file_name: &'static str,
    pub file_size_bytes: u64,
    pub sha256_checksum: Option<&'static str>,
    pub description: &'static str,
    pub speed: &'static str,
    pub accuracy: &'static str,
    pub category: &'static str,
    pub recommended_for: &'static str,
    pub engine: &'static str,
    pub artifact_format: &'static str,
    pub runtime: &'static str,
    pub supports_streaming: bool,
    pub supports_word_timestamps: bool,
    pub supports_confidence: bool,
    pub license_id: &'static str,
    pub license_url: &'static str,
    pub language_locales: &'static [&'static str],
}

const WHISPER_LANGS: &[&str] = &[
    "auto", "de", "en", "fr", "es", "it", "pt", "nl", "pl", "ru", "ja", "zh",
];
const EN_ONLY: &[&str] = &["en"];
const PARAKEET_TDT_V3_LANGS: &[&str] = &[
    "bg", "hr", "cs", "da", "nl", "en", "et", "fi", "fr", "de", "el", "hu", "it", "lv", "lt", "mt",
    "pl", "pt", "ro", "sk", "sl", "es", "sv", "ru", "uk",
];
const NEMOTRON_LANGS: &[&str] = &[
    "auto", "en-US", "en-GB", "es-US", "es-ES", "fr-FR", "fr-CA", "it-IT", "pt-BR", "pt-PT",
    "nl-NL", "de-DE", "tr-TR", "ru-RU", "ar-AR", "hi-IN", "ja-JP", "ko-KR", "vi-VN", "uk-UA",
    "pl-PL", "sv-SE", "cs-CZ", "nb-NO", "da-DK", "bg-BG", "fi-FI", "hr-HR", "sk-SK", "zh-CN",
    "hu-HU", "ro-RO", "et-EE", "el-GR", "lt-LT", "lv-LV", "mt-MT", "sl-SI", "he-IL", "th-TH",
    "nn-NO",
];

pub static REGISTRY: &[ModelDefinition] = &[
    whisper_model(
        "ggml-tiny",
        "Tiny",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin",
        "ggml-tiny.bin",
        77_704_715,
        "Smallest model, runs on any hardware. Limited accuracy but usable for simple dictation.",
        "fastest",
        "low",
        "standard",
        "Quick tests, very old hardware",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-tiny-q8",
        "Tiny Q8",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny-q8_0.bin",
        "ggml-tiny-q8.bin",
        43_614_209,
        "Tiny quantized to 8-bit. Half the size with nearly identical quality.",
        "fastest",
        "low",
        "quantized",
        "Minimal RAM, embedded or low-end devices",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-tiny-en",
        "Tiny (EN only)",
        "en-only",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin",
        "ggml-tiny-en.bin",
        77_704_715,
        "English-only Tiny. Slightly better English accuracy than the multilingual version.",
        "fastest",
        "low",
        "standard",
        "English-only, minimal resources",
        EN_ONLY,
    ),
    whisper_model(
        "ggml-base",
        "Base",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin",
        "ggml-base.bin",
        147_964_211,
        "Good balance of speed and accuracy for everyday dictation. Solid DE/EN support.",
        "fast",
        "medium",
        "standard",
        "Daily dictation, DE + EN",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-base-q8",
        "Base Q8",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base-q8_0.bin",
        "ggml-base-q8.bin",
        81_773_312,
        "Base quantized to 8-bit - 45% smaller, nearly identical accuracy.",
        "fast",
        "medium",
        "quantized",
        "Best size/quality ratio for Base",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-small",
        "Small",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin",
        "ggml-small.bin",
        487_601_739,
        "Noticeably better accuracy than Base, still fast enough on modern CPUs.",
        "balanced",
        "good",
        "standard",
        "Good accuracy without GPU",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-small-q8",
        "Small Q8",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small-q8_0.bin",
        "ggml-small-q8.bin",
        263_819_264,
        "Small quantized to 8-bit - 46% smaller with minimal quality loss.",
        "balanced",
        "good",
        "quantized",
        "Best size/quality ratio for Small",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-medium",
        "Medium",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin",
        "ggml-medium.bin",
        1_533_774_855,
        "High accuracy for complex vocabulary and accents. Requires about 4 GB RAM.",
        "slow",
        "great",
        "standard",
        "Complex vocabulary, technical terms",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-medium-q5",
        "Medium Q5",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium-q5_0.bin",
        "ggml-medium-q5.bin",
        539_212_800,
        "Medium at 5-bit quantization - much smaller than full Medium.",
        "balanced",
        "great",
        "quantized",
        "Medium quality at Small size",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-large-v3-turbo-q5",
        "Large v3 Turbo Q5",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q5_0.bin",
        "ggml-large-v3-turbo-q5.bin",
        574_000_000,
        "Large-v3-Turbo at 5-bit quantization. Best overall Whisper pick.",
        "fast",
        "best",
        "turbo",
        "Best Whisper accuracy/speed ratio",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-large-v3-turbo-q8",
        "Large v3 Turbo Q8",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q8_0.bin",
        "ggml-large-v3-turbo-q8.bin",
        874_000_000,
        "Large-v3-Turbo at 8-bit quantization. Slightly better for noisy audio.",
        "fast",
        "best",
        "turbo",
        "Noisy environments, high accuracy",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-large-v3-turbo",
        "Large v3 Turbo",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin",
        "ggml-large-v3-turbo.bin",
        1_620_000_000,
        "Full-precision Large-v3-Turbo. 8x faster than Large-v3.",
        "balanced",
        "best",
        "turbo",
        "Maximum Turbo accuracy, no quantization",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-large-v3-q5",
        "Large v3 Q5",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-q5_0.bin",
        "ggml-large-v3-q5.bin",
        1_080_000_000,
        "OpenAI's best Whisper model at 5-bit quantization.",
        "slow",
        "best",
        "large",
        "Highest Whisper accuracy, powerful hardware",
        WHISPER_LANGS,
    ),
    whisper_model(
        "ggml-large-v3",
        "Large v3",
        "multilingual",
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
        "ggml-large-v3.bin",
        3_100_000_000,
        "Full-precision Large-v3. Requires about 10 GB RAM.",
        "slowest",
        "best",
        "large",
        "Maximum Whisper accuracy, GPU recommended",
        WHISPER_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-nemotron-3-5-streaming-0-6b-q4",
        "Nemotron 3.5 ASR Streaming Q4",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/nemotron-3.5-asr-streaming-0.6b-q4_k.gguf",
        "nemotron-3.5-asr-streaming-0.6b-q4_k.gguf",
        718_102_624,
        "5ad85eb3f3014c1a300d67b7ccbd23c38c4c952405cbe33a861e19fb2775e84b",
        "Compact multilingual cache-aware streaming model for Parakeet.cpp.",
        "fast",
        "great",
        "parakeet",
        "Portable multilingual streaming on constrained storage",
        "openmdw-1.1",
        "https://openmdw.ai/license/1-1/",
        NEMOTRON_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-nemotron-3-5-streaming-0-6b-q5",
        "Nemotron 3.5 ASR Streaming Q5",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/nemotron-3.5-asr-streaming-0.6b-q5_k.gguf",
        "nemotron-3.5-asr-streaming-0.6b-q5_k.gguf",
        784_801_888,
        "7bb14605a707f821560952521034002c91653d676272a80dca0cd2aa886d0ab2",
        "Recommended portable multilingual cache-aware streaming model.",
        "fast",
        "best",
        "parakeet",
        "Default Parakeet streaming choice",
        "openmdw-1.1",
        "https://openmdw.ai/license/1-1/",
        NEMOTRON_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-nemotron-3-5-streaming-0-6b-q8",
        "Nemotron 3.5 ASR Streaming Q8",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/nemotron-3.5-asr-streaming-0.6b-q8_0.gguf",
        "nemotron-3.5-asr-streaming-0.6b-q8_0.gguf",
        983_696_512,
        "ba2f13eccd4a5245be728f77e6149bd6a4fdcdd133ff2e08ac6005bcef7a99f1",
        "Higher precision Nemotron GGUF runtime with stronger quality headroom.",
        "balanced",
        "best",
        "parakeet",
        "High quality portable streaming",
        "openmdw-1.1",
        "https://openmdw.ai/license/1-1/",
        NEMOTRON_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-nemotron-3-5-streaming-0-6b-f16",
        "Nemotron 3.5 ASR Streaming F16",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/nemotron-3.5-asr-streaming-0.6b-f16.gguf",
        "nemotron-3.5-asr-streaming-0.6b-f16.gguf",
        1_484_324_992,
        "b64413c3886edf2b45eb3e757f911f1bc8020b7cf157622cd0bd0452c6d84aac",
        "Full precision Nemotron GGUF for Parakeet.cpp.",
        "balanced",
        "best",
        "parakeet",
        "Maximum GGUF quality",
        "openmdw-1.1",
        "https://openmdw.ai/license/1-1/",
        NEMOTRON_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-tdt-0-6b-v3-q4",
        "Parakeet TDT 0.6B v3 Q4",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/tdt-0.6b-v3-q4_k.gguf",
        "tdt-0.6b-v3-q4_k.gguf",
        675_200_864,
        "993d73feb4206dadda865ab25bd64b50c48dc4d013c3bf6126a721f28b1d5ee8",
        "Compact offline multilingual Parakeet TDT v3 model.",
        "fast",
        "great",
        "parakeet",
        "Portable offline multilingual dictation",
        "cc-by-4.0",
        "https://creativecommons.org/licenses/by/4.0/legalcode",
        PARAKEET_TDT_V3_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-tdt-0-6b-v3-q5",
        "Parakeet TDT 0.6B v3 Q5",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/tdt-0.6b-v3-q5_k.gguf",
        "tdt-0.6b-v3-q5_k.gguf",
        741_867_360,
        "5ebd1d55609b5ad9dac1c457eeb87a9904f199d6fbbb738453182d010646c2e4",
        "Recommended offline multilingual Parakeet TDT v3 model.",
        "fast",
        "best",
        "parakeet",
        "High quality offline multilingual dictation",
        "cc-by-4.0",
        "https://creativecommons.org/licenses/by/4.0/legalcode",
        PARAKEET_TDT_V3_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-tdt-0-6b-v3-q8",
        "Parakeet TDT 0.6B v3 Q8",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/tdt-0.6b-v3-q8_0.gguf",
        "tdt-0.6b-v3-q8_0.gguf",
        940_663_680,
        "4d69a4a6683f4f2d952bad794c1357ca6eb628027695b4699c5a9ad4cd07d757",
        "Higher precision offline multilingual Parakeet TDT v3 model.",
        "balanced",
        "best",
        "parakeet",
        "Noisy multilingual offline dictation",
        "cc-by-4.0",
        "https://creativecommons.org/licenses/by/4.0/legalcode",
        PARAKEET_TDT_V3_LANGS,
    ),
    parakeet_cpp_model(
        "parakeet-tdt-0-6b-v3-f16",
        "Parakeet TDT 0.6B v3 F16",
        "https://huggingface.co/mudler/parakeet-cpp-gguf/resolve/main/tdt-0.6b-v3-f16.gguf",
        "tdt-0.6b-v3-f16.gguf",
        1_441_046_400,
        "8ba47343e1e919895aca90e099150a01ed203ee0942d8ed31e27295efc5abb22",
        "Full precision offline multilingual Parakeet TDT v3 model.",
        "balanced",
        "best",
        "parakeet",
        "Maximum TDT v3 quality",
        "cc-by-4.0",
        "https://creativecommons.org/licenses/by/4.0/legalcode",
        PARAKEET_TDT_V3_LANGS,
    ),
    nemo_model(
        "nemo-nemotron-3-5-streaming-0-6b",
        "Nemotron 3.5 ASR Streaming (.nemo)",
        "https://huggingface.co/nvidia/nemotron-3.5-asr-streaming-0.6b/resolve/main/nemotron-3.5-asr-streaming-0.6b.nemo",
        "nemotron-3.5-asr-streaming-0.6b.nemo",
        2_368_284_501,
        "210214ed94039bf6bfbb9a047c7fa289628db75b103e2bf6381fa78285436a74",
        "NVIDIA-native multilingual streaming checkpoint. Requires optional NeMo runtime.",
        "balanced",
        "best",
        "nemo",
        "Highest fidelity NVIDIA-native multilingual streaming",
        "openmdw-1.1",
        "https://openmdw.ai/license/1-1/",
        NEMOTRON_LANGS,
    ),
    nemo_model(
        "nemo-parakeet-tdt-0-6b-v3",
        "Parakeet TDT 0.6B v3 (.nemo)",
        "https://huggingface.co/nvidia/parakeet-tdt-0.6b-v3/resolve/main/parakeet-tdt-0.6b-v3.nemo",
        "parakeet-tdt-0.6b-v3.nemo",
        2_509_332_480,
        "3cbdc85877e668ca7b82d0d56770eb1fac76691f55d6b97545e8d61ca588d10d",
        "NVIDIA-native offline multilingual Parakeet TDT v3 checkpoint. Requires optional NeMo runtime.",
        "balanced",
        "best",
        "nemo",
        "Highest fidelity offline Parakeet v3 transcription",
        "cc-by-4.0",
        "https://creativecommons.org/licenses/by/4.0/legalcode",
        PARAKEET_TDT_V3_LANGS,
    ),
];

pub fn find(key: &str) -> Option<&'static ModelDefinition> {
    REGISTRY.iter().find(|m| m.key == key)
}

const fn whisper_model(
    key: &'static str,
    display_name: &'static str,
    language_scope: &'static str,
    download_url: &'static str,
    file_name: &'static str,
    file_size_bytes: u64,
    description: &'static str,
    speed: &'static str,
    accuracy: &'static str,
    category: &'static str,
    recommended_for: &'static str,
    language_locales: &'static [&'static str],
) -> ModelDefinition {
    ModelDefinition {
        key,
        display_name,
        language_scope,
        download_url,
        file_name,
        file_size_bytes,
        sha256_checksum: None,
        description,
        speed,
        accuracy,
        category,
        recommended_for,
        engine: ENGINE_WHISPER_CPP,
        artifact_format: FORMAT_GGML_BIN,
        runtime: RUNTIME_BUNDLED_SIDECAR,
        supports_streaming: false,
        supports_word_timestamps: false,
        supports_confidence: true,
        license_id: "mit",
        license_url: "https://github.com/ggerganov/whisper.cpp",
        language_locales,
    }
}

#[allow(clippy::too_many_arguments)]
const fn parakeet_cpp_model(
    key: &'static str,
    display_name: &'static str,
    download_url: &'static str,
    file_name: &'static str,
    file_size_bytes: u64,
    checksum: &'static str,
    description: &'static str,
    speed: &'static str,
    accuracy: &'static str,
    category: &'static str,
    recommended_for: &'static str,
    license_id: &'static str,
    license_url: &'static str,
    language_locales: &'static [&'static str],
) -> ModelDefinition {
    ModelDefinition {
        key,
        display_name,
        language_scope: "multilingual",
        download_url,
        file_name,
        file_size_bytes,
        sha256_checksum: Some(checksum),
        description,
        speed,
        accuracy,
        category,
        recommended_for,
        engine: ENGINE_PARAKEET_CPP,
        artifact_format: FORMAT_GGUF,
        runtime: RUNTIME_BUNDLED_SIDECAR,
        supports_streaming: true,
        supports_word_timestamps: true,
        supports_confidence: true,
        license_id,
        license_url,
        language_locales,
    }
}

#[allow(clippy::too_many_arguments)]
const fn nemo_model(
    key: &'static str,
    display_name: &'static str,
    download_url: &'static str,
    file_name: &'static str,
    file_size_bytes: u64,
    checksum: &'static str,
    description: &'static str,
    speed: &'static str,
    accuracy: &'static str,
    category: &'static str,
    recommended_for: &'static str,
    license_id: &'static str,
    license_url: &'static str,
    language_locales: &'static [&'static str],
) -> ModelDefinition {
    ModelDefinition {
        key,
        display_name,
        language_scope: "multilingual",
        download_url,
        file_name,
        file_size_bytes,
        sha256_checksum: Some(checksum),
        description,
        speed,
        accuracy,
        category,
        recommended_for,
        engine: ENGINE_NEMO,
        artifact_format: FORMAT_NEMO,
        runtime: RUNTIME_OPTIONAL_NEMO,
        supports_streaming: false,
        supports_word_timestamps: true,
        supports_confidence: true,
        license_id,
        license_url,
        language_locales,
    }
}
